### ISSUE TITLE
Clearer commands

### ISSUE THREAD

**Issue by bumblepie** [denko-co/dee-emcy#13]
Currently there is some confusion when submitting questions and answers, and we end up with answers in the dmcs and vice versa. One possible solution is to ask for confirmation before posting. I think a better solution would be to limit the available commands to make the user's intent more clearly explicit. Ie: only allow [dmc|spd|answer] "XYZ....". Additionally, a help command would go a long way towards improving usability.

**Comment by franomai** [comment]
Done as part of Version 1.6
