### ISSUE TITLE
Questions sometimes don't register

### ISSUE THREAD

**Issue by SarenCurrie** [denko-co/dee-emcy#4]
When submitting a question, sometime you have to send it twice for the bot to acknowledge it. The first time, it responds with the help text of how to submit.

**Comment by franomai** [comment]
This is because if the database doesn't have the user, it will give it the 'how to use me' explanation, then it will start receiving. You're right though, that if they do post a valid question in the format, it should skip that and let them submit.

**Comment by franomai** [comment]
Fixed in version 1.3! <3
