### ISSUE TITLE
Downvote question cycling can be repeated ad infinitum by removing then readding reactions

### ISSUE THREAD

**Issue by SarenCurrie** [denko-co/dee-emcy#5]
Removing a downvote reaction then readding it when the question is on the downvote limit will cause the question cycling to trigger again.

**Comment by franomai** [comment]
Oh noes! I'm out of questions! I'll go take a nap, send me a DM so we have something exciting to talk about tomorrow! <3

**Comment by franomai** [comment]
Fixed in version 1.3! <3
