### ISSUE TITLE
Duplicate questions aren't saved again, but the user doesn't know that.

### ISSUE THREAD

**Issue by franomai** [denko-co/dee-emcy#6]
Need to make a call whether we say 'sorry, no can do' or just allow the dupe. What do you think @greg737 ?

**Comment by greg737** [comment]
I say allow the dupe would be easier but if we do that, would we have to refresh/overwrite the other info attached to the msg object like author and id or react counts in the future?

**Comment by franomai** [comment]
Fixed in version 1.3! <3
