### ISSUE TITLE
DMC's reacts count towards up/down

### ISSUE THREAD

**Issue by bumblepie** [denko-co/dee-emcy#9]
When DMC posts that she has a new question (after running out) she only posts the upvote reaction, and it counts towards the reacts needed to trigger the question. Thus only 2 reacts are needed rather than 3.

**Comment by franomai** [comment]
I'll fix this for v1.4 (which will include a change to the restart dialog) - @greg737, for that, should the bot PM one of us to say there is a restart? I am going to stop it spamming the release notes and only post them if it's actually a new version.

**Comment by franomai** [comment]
Handled in v1.4, closing this out!
